# Generated by Django 5.0.6 on 2024-05-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStore',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_image', models.ImageField(upload_to='images/')),
                ('store_name', models.CharField(max_length=500)),
                ('rate', models.IntegerField()),
            ],
            options={
                'db_table': 'store_table',
            },
        ),
    ]
