# Generated by Django 4.2.7 on 2024-05-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_regular_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selected_countries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
