# Generated by Django 4.2.7 on 2024-05-23 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_refundorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
