# Generated by Django 4.2.7 on 2024-05-23 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_refundorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_product', to='products.product'),
        ),
    ]
